class DiagnosticForm {
    constructor (
      public id: string,
      public titulo: string,
      public acidenteOption: string,
      public acidenterespsim: string,
      public aidsOption: string,
      public anemiaOption: string,
      public bebidas: string,
      public bebidasrespsimqual: string,
      public bebidasrespsimtempo: string,
      public consistenciaOption: string,
      public cor: string,
      public datanascimento: string,
      public diabetesOption: string,
      public diagnosticoclinico: string,
      public drogasrespsimqual: string,
      public drogasrespsimtempo: string,
      public drogasOption: string,
      public dstOption: string,
      public escolaridadeOption: string,
      public estadocivilOption: string,
      public exfumanteOption: string,
      public exfumanterespsimtempo: string,
      public fatoretiologico: string,
      public forma: string,
      public fumanteOption: string,
      public fumanterespsimquant: string,
      public fumanterespsimtempo: string,
      public gangliosOption: string,
      public gangliosrespsim: string,
      public hepatiteOption: string,
      public histopatologico: string,
      public insercao: string,
      public localizacao: string,
      public medicamentoOption: string,
      public medicamentorespsim: string,
      public mobilidadeOption: string,
      public naturalidade: string,
      public nome: string,
      public pressaoaltaOption: string,
      public profissao: string,
      public tamanho: string,
      public tratamentomedico: string,
      public tratamentomedicoOption: string,
      public tratamentomedicosim: string,
      public sexoOption: string
    ) {}
}

export { DiagnosticForm };
